import Question from '#domains/Question/Models/Question'

// Constants cho seeder - sử dụng các giá trị giống với frontend
const QUESTION_TYPES = {
  TRUE_FALSE: 'true_false',
  SINGLE_CHOICE: 'single_choice',
  MULTIPLE_CHOICE: 'multiple_choice',
  FILL_BLANK: 'fill_blank',
}

const DIFFICULTY_LEVELS = {
  EASY: 'easy',
  MEDIUM: 'medium',
  HARD: 'hard',
}

const CLASS_4 = 'LOP_4'

export default class QuestionSeeder {
  async run() {
    console.log('🌱 Seeding 80 questions for Lớp 3 (Easy, Medium & Hard levels)...')

    const questions = [
      // True/False Questions (8 câu)
      {
        title: 'Phép cộng cơ bản',
        content: '5 + 3 = 8 là phép tính đúng?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: '5 + 3 thực sự bằng 8' },
          { text: 'Sai', isCorrect: false, explanation: 'Đây là phép tính đúng' },
        ],
        explanation: 'Phép cộng cơ bản: 5 cộng 3 bằng 8',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['toán', 'cộng', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phép trừ cơ bản',
        content: '10 - 4 = 6 là phép tính đúng?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: '10 - 4 thực sự bằng 6' },
          { text: 'Sai', isCorrect: false, explanation: 'Đây là phép tính đúng' },
        ],
        explanation: 'Phép trừ cơ bản: 10 trừ 4 bằng 6',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['toán', 'trừ', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Động vật có 4 chân',
        content: 'Chó là động vật có 4 chân?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Chó có 4 chân' },
          { text: 'Sai', isCorrect: false, explanation: 'Chó thực sự có 4 chân' },
        ],
        explanation: 'Chó là động vật có vú có 4 chân',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['sinh học', 'động vật', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Trộn màu cơ bản',
        content: 'Đỏ và vàng trộn lại tạo thành màu cam?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Đỏ + vàng = cam' },
          { text: 'Sai', isCorrect: false, explanation: 'Đây là quy tắc trộn màu đúng' },
        ],
        explanation: 'Khi trộn màu đỏ và vàng sẽ tạo ra màu cam',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['mỹ thuật', 'màu sắc', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Thời gian trong tuần',
        content: 'Một tuần có 7 ngày?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Một tuần có 7 ngày' },
          { text: 'Sai', isCorrect: false, explanation: 'Một tuần thực sự có 7 ngày' },
        ],
        explanation: 'Một tuần bao gồm 7 ngày từ thứ 2 đến chủ nhật',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['thời gian', 'tuần', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Cơ thể con người',
        content: 'Con người có 5 ngón tay ở mỗi bàn tay?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Mỗi bàn tay có 5 ngón' },
          { text: 'Sai', isCorrect: false, explanation: 'Con người có 5 ngón tay ở mỗi bàn tay' },
        ],
        explanation:
          'Bàn tay con người có 5 ngón: ngón cái, ngón trỏ, ngón giữa, ngón áp út, ngón út',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['sinh học', 'cơ thể', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Hình dạng cơ bản',
        content: 'Hình tròn không có góc?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Hình tròn không có góc nào' },
          { text: 'Sai', isCorrect: false, explanation: 'Hình tròn thực sự không có góc' },
        ],
        explanation: 'Hình tròn là hình cong không có góc',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['toán', 'hình học', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Mặt trời và ban ngày',
        content: 'Mặt trời tỏa sáng vào ban ngày?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Mặt trời chiếu sáng ban ngày' },
          { text: 'Sai', isCorrect: false, explanation: 'Mặt trời thực sự tỏa sáng ban ngày' },
        ],
        explanation: 'Mặt trời là nguồn sáng tự nhiên ban ngày',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 1,
        class: CLASS_4,
        tags: ['khoa học', 'thiên nhiên', 'lớp 3'],
        isActive: true,
      },

      // Single Choice Questions (12 câu)
      {
        title: 'Phép cộng đơn giản',
        content: '4 + 5 = ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '8', isCorrect: false, explanation: '4 + 5 không bằng 8' },
          { text: '9', isCorrect: true, explanation: '4 + 5 = 9' },
          { text: '10', isCorrect: false, explanation: '4 + 5 không bằng 10' },
          { text: '11', isCorrect: false, explanation: '4 + 5 không bằng 11' },
        ],
        explanation: 'Phép cộng: 4 cộng 5 bằng 9',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'cộng', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn con vật có thể bay',
        content: 'Con vật nào có thể bay?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Chó', isCorrect: false, explanation: 'Chó không thể bay' },
          { text: 'Mèo', isCorrect: false, explanation: 'Mèo không thể bay' },
          { text: 'Chim', isCorrect: true, explanation: 'Chim có thể bay' },
          { text: 'Cá', isCorrect: false, explanation: 'Cá không thể bay' },
        ],
        explanation: 'Chim có cánh nên có thể bay',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['sinh học', 'động vật', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phép trừ đơn giản',
        content: '8 - 3 = ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '4', isCorrect: false, explanation: '8 - 3 không bằng 4' },
          { text: '5', isCorrect: true, explanation: '8 - 3 = 5' },
          { text: '6', isCorrect: false, explanation: '8 - 3 không bằng 6' },
          { text: '7', isCorrect: false, explanation: '8 - 3 không bằng 7' },
        ],
        explanation: 'Phép trừ: 8 trừ 3 bằng 5',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'trừ', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn màu được tạo từ xanh và vàng',
        content: 'Màu gì được tạo ra khi trộn xanh dương và vàng?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Đỏ', isCorrect: false, explanation: 'Xanh dương + vàng không tạo màu đỏ' },
          { text: 'Tím', isCorrect: false, explanation: 'Xanh dương + vàng không tạo màu tím' },
          { text: 'Xanh lá', isCorrect: true, explanation: 'Xanh dương + vàng = xanh lá' },
          { text: 'Cam', isCorrect: false, explanation: 'Xanh dương + vàng không tạo màu cam' },
        ],
        explanation: 'Khi trộn màu xanh dương và vàng sẽ tạo ra màu xanh lá cây',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['mỹ thuật', 'màu sắc', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phép nhân đơn giản',
        content: '3 × 2 = ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '5', isCorrect: false, explanation: '3 × 2 không bằng 5' },
          { text: '6', isCorrect: true, explanation: '3 × 2 = 6' },
          { text: '7', isCorrect: false, explanation: '3 × 2 không bằng 7' },
          { text: '8', isCorrect: false, explanation: '3 × 2 không bằng 8' },
        ],
        explanation: 'Phép nhân: 3 nhân 2 bằng 6',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'nhân', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn hình có 3 cạnh',
        content: 'Hình nào có 3 cạnh?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Hình vuông', isCorrect: false, explanation: 'Hình vuông có 4 cạnh' },
          { text: 'Hình tròn', isCorrect: false, explanation: 'Hình tròn không có cạnh' },
          { text: 'Hình tam giác', isCorrect: true, explanation: 'Hình tam giác có 3 cạnh' },
          { text: 'Hình chữ nhật', isCorrect: false, explanation: 'Hình chữ nhật có 4 cạnh' },
        ],
        explanation: 'Hình tam giác là hình có 3 cạnh và 3 góc',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'hình học', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn phương tiện di chuyển trên nước',
        content: 'Phương tiện nào di chuyển trên nước?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Ô tô', isCorrect: false, explanation: 'Ô tô chạy trên đường' },
          { text: 'Máy bay', isCorrect: false, explanation: 'Máy bay bay trên trời' },
          { text: 'Thuyền', isCorrect: true, explanation: 'Thuyền di chuyển trên nước' },
          { text: 'Xe đạp', isCorrect: false, explanation: 'Xe đạp chạy trên đường' },
        ],
        explanation: 'Thuyền là phương tiện di chuyển trên mặt nước',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['xã hội', 'giao thông', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn bộ phận giúp nhìn',
        content: 'Bộ phận nào giúp ta nhìn thấy?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Tai', isCorrect: false, explanation: 'Tai giúp ta nghe' },
          { text: 'Mắt', isCorrect: true, explanation: 'Mắt giúp ta nhìn thấy' },
          { text: 'Mũi', isCorrect: false, explanation: 'Mũi giúp ta ngửi' },
          { text: 'Miệng', isCorrect: false, explanation: 'Miệng giúp ta nói và ăn' },
        ],
        explanation: 'Mắt là cơ quan thị giác giúp chúng ta nhìn thấy',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['sinh học', 'cơ thể', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn mùa trong năm',
        content: 'Mùa nào lá cây rụng nhiều?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Mùa xuân', isCorrect: false, explanation: 'Mùa xuân lá cây xanh tốt' },
          { text: 'Mùa hè', isCorrect: false, explanation: 'Mùa hè lá cây xanh um' },
          { text: 'Mùa thu', isCorrect: true, explanation: 'Mùa thu lá cây thường rụng' },
          { text: 'Mùa đông', isCorrect: false, explanation: 'Mùa đông lá đã rụng hết' },
        ],
        explanation: 'Mùa thu là thời điểm lá cây chuyển màu và rụng nhiều',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['khoa học', 'thiên nhiên', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn số lớn nhất',
        content: 'Số nào lớn nhất trong các số sau?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '5', isCorrect: false, explanation: '5 không phải số lớn nhất' },
          { text: '8', isCorrect: false, explanation: '8 không phải số lớn nhất' },
          { text: '12', isCorrect: true, explanation: '12 là số lớn nhất' },
          { text: '9', isCorrect: false, explanation: '9 không phải số lớn nhất' },
        ],
        explanation: 'So sánh các số: 12 > 9 > 8 > 5',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'so sánh', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn con vật sống ở nông trại',
        content: 'Con vật nào thường được nuôi ở nông trại?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Sư tử', isCorrect: false, explanation: 'Sư tử sống ở động vật hoang dã' },
          { text: 'Bò', isCorrect: true, explanation: 'Bò được nuôi ở nông trại' },
          { text: 'Cá mập', isCorrect: false, explanation: 'Cá mập sống ở biển' },
          { text: 'Đại bàng', isCorrect: false, explanation: 'Đại bàng sống ở núi cao' },
        ],
        explanation: 'Bò là động vật gia súc được nuôi phổ biến ở nông trại',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['sinh học', 'động vật', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn loại quả có màu đỏ',
        content: 'Quả nào có màu đỏ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Chuối', isCorrect: false, explanation: 'Chuối có màu vàng' },
          { text: 'Táo đỏ', isCorrect: true, explanation: 'Táo đỏ có màu đỏ' },
          { text: 'Cam', isCorrect: false, explanation: 'Cam có màu cam' },
          { text: 'Nho xanh', isCorrect: false, explanation: 'Nho xanh có màu xanh' },
        ],
        explanation: 'Táo đỏ là loại quả có màu đỏ tươi',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['sinh học', 'thực vật', 'lớp 3'],
        isActive: true,
      },

      // Multiple Choice Questions (5 câu)
      {
        title: 'Chọn các số chẵn',
        content: 'Trong các số sau, số nào là số chẵn?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: '2', isCorrect: true, explanation: '2 chia hết cho 2' },
          { text: '3', isCorrect: false, explanation: '3 không chia hết cho 2' },
          { text: '4', isCorrect: true, explanation: '4 chia hết cho 2' },
          { text: '5', isCorrect: false, explanation: '5 không chia hết cho 2' },
          { text: '6', isCorrect: true, explanation: '6 chia hết cho 2' },
        ],
        explanation: 'Số chẵn là số chia hết cho 2',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'số chẵn', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các loại quả',
        content: 'Đâu là các loại quả?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: 'Táo', isCorrect: true, explanation: 'Táo là loại quả' },
          { text: 'Cà rót', isCorrect: false, explanation: 'Cà rót là loại rau' },
          { text: 'Cam', isCorrect: true, explanation: 'Cam là loại quả' },
          { text: 'Xoài', isCorrect: true, explanation: 'Xoài là loại quả' },
          { text: 'Rau muống', isCorrect: false, explanation: 'Rau muống là loại rau' },
        ],
        explanation: 'Quả là phần chứa hạt của cây, thường có vị ngọt',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 3,
        class: CLASS_4,
        tags: ['sinh học', 'thực vật', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các hình có 4 cạnh',
        content: 'Hình nào có 4 cạnh?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: 'Hình vuông', isCorrect: true, explanation: 'Hình vuông có 4 cạnh bằng nhau' },
          { text: 'Hình tam giác', isCorrect: false, explanation: 'Hình tam giác có 3 cạnh' },
          { text: 'Hình chữ nhật', isCorrect: true, explanation: 'Hình chữ nhật có 4 cạnh' },
          { text: 'Hình tròn', isCorrect: false, explanation: 'Hình tròn không có cạnh' },
          { text: 'Hình thoi', isCorrect: true, explanation: 'Hình thoi có 4 cạnh bằng nhau' },
        ],
        explanation: 'Các hình tứ giác đều có 4 cạnh',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'hình học', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các màu cơ bản',
        content: 'Đâu là các màu cơ bản?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: 'Đỏ', isCorrect: true, explanation: 'Đỏ là màu cơ bản' },
          { text: 'Cam', isCorrect: false, explanation: 'Cam là màu thứ cấp (đỏ + vàng)' },
          { text: 'Vàng', isCorrect: true, explanation: 'Vàng là màu cơ bản' },
          { text: 'Xanh dương', isCorrect: true, explanation: 'Xanh dương là màu cơ bản' },
          { text: 'Tím', isCorrect: false, explanation: 'Tím là màu thứ cấp (đỏ + xanh dương)' },
        ],
        explanation: 'Ba màu cơ bản là đỏ, vàng, xanh dương',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 3,
        class: CLASS_4,
        tags: ['mỹ thuật', 'màu sắc', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các con vật sống trong nước',
        content: 'Con vật nào sống trong nước?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: 'Cá', isCorrect: true, explanation: 'Cá sống trong nước' },
          { text: 'Chó', isCorrect: false, explanation: 'Chó sống trên cạn' },
          { text: 'Ếch', isCorrect: true, explanation: 'Ếch sống cả trong nước và trên cạn' },
          { text: 'Rùa', isCorrect: true, explanation: 'Có loại rùa sống trong nước' },
          { text: 'Mèo', isCorrect: false, explanation: 'Mèo sống trên cạn' },
        ],
        explanation: 'Động vật sống ở nước thích nghi với môi trường nước',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 3,
        class: CLASS_4,
        tags: ['sinh học', 'động vật', 'lớp 3'],
        isActive: true,
      },

      // Fill in the Blank Questions (5 câu)
      {
        title: 'Điền số vào phép cộng',
        content: '3 + ___ = 7',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '4', isCorrect: true, explanation: '3 + 4 = 7' },
          { text: 'bốn', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        explanation: 'Ta có 7 - 3 = 4, nên 3 + 4 = 7',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'cộng', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền thủ đô Việt Nam',
        content: 'Thủ đô của Việt Nam là ___',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: 'Hà Nội', isCorrect: true, explanation: 'Hà Nội là thủ đô của Việt Nam' },
          { text: 'ha noi', isCorrect: true, explanation: 'Viết thường cũng được chấp nhận' },
          { text: 'HÀ NỘI', isCorrect: true, explanation: 'Viết hoa cũng được chấp nhận' },
        ],
        explanation: 'Hà Nội là thủ đô chính thức của nước Cộng hòa Xã hội Chủ nghĩa Việt Nam',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['địa lý', 'việt nam', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền số ngón tay',
        content: 'Mỗi bàn tay có ___ ngón tay',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '5', isCorrect: true, explanation: 'Mỗi bàn tay có 5 ngón' },
          { text: 'năm', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        explanation:
          'Bàn tay con người có 5 ngón: ngón cái, ngón trỏ, ngón giữa, ngón áp út, ngón út',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['sinh học', 'cơ thể', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền số cạnh hình tam giác',
        content: 'Hình tam giác có ___ cạnh',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '3', isCorrect: true, explanation: 'Hình tam giác có 3 cạnh' },
          { text: 'ba', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        explanation: 'Hình tam giác là hình có 3 cạnh và 3 góc',
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'hình học', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền kết quả phép nhân',
        content: '2 × 4 = ___',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '8', isCorrect: true, explanation: '2 × 4 = 8' },
          { text: 'tám', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        difficulty: DIFFICULTY_LEVELS.EASY,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'nhân', 'lớp 3'],
        isActive: true,
      },

      // MEDIUM DIFFICULTY QUESTIONS (30 câu)
      // True/False Questions - Medium (8 câu)
      {
        title: 'Phép chia cơ bản',
        content: '20 ÷ 5 = 4 là phép tính đúng?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: '20 ÷ 5 = 4' },
          { text: 'Sai', isCorrect: false, explanation: 'Đây là phép chia đúng' },
        ],
        explanation: 'Phép chia: 20 chia 5 bằng 4',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'chia', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'So sánh số',
        content: '25 > 30 là so sánh đúng?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: false, explanation: '25 nhỏ hơn 30, không lớn hơn' },
          { text: 'Sai', isCorrect: true, explanation: '25 < 30, nên 25 > 30 là sai' },
        ],
        explanation: 'So sánh: 25 nhỏ hơn 30, vậy 25 > 30 là sai',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'so sánh', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chu vi hình vuông',
        content: 'Chu vi hình vuông cạnh 5cm là 20cm?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Chu vi = 4 × 5 = 20cm' },
          {
            text: 'Sai',
            isCorrect: false,
            explanation: 'Chu vi hình vuông cạnh 5cm thực sự là 20cm',
          },
        ],
        explanation: 'Chu vi hình vuông = 4 × cạnh = 4 × 5 = 20cm',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'hình học', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phân số đơn giản',
        content: '1/2 lớn hơn 1/4?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: '1/2 = 0.5, 1/4 = 0.25, nên 1/2 > 1/4' },
          { text: 'Sai', isCorrect: false, explanation: '1/2 thực sự lớn hơn 1/4' },
        ],
        explanation: 'Khi so sánh phân số: 1/2 = 2/4, và 2/4 > 1/4',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['toán', 'phân số', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chuỗi thức ăn',
        content: 'Thỏ ăn thịt động vật khác?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: false, explanation: 'Thỏ là động vật ăn cỏ' },
          { text: 'Sai', isCorrect: true, explanation: 'Thỏ chỉ ăn thực vật, không ăn thịt' },
        ],
        explanation: 'Thỏ là động vật ăn cỏ (herbivore), chỉ ăn thực vật',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['sinh học', 'động vật', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chu kỳ nước',
        content: 'Nước biển bay hơi tạo thành mây?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Nước biển bay hơi lên tạo thành mây' },
          { text: 'Sai', isCorrect: false, explanation: 'Đây là một phần của chu kỳ nước' },
        ],
        explanation: 'Chu kỳ nước: nước biển bay hơi → hơi nước tụ thành mây → mưa',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['khoa học', 'chu kỳ nước', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Lịch sử Việt Nam',
        content: 'Hồ Chí Minh sinh ở Nghệ An?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: 'Hồ Chí Minh sinh tại làng Sen, Nghệ An' },
          { text: 'Sai', isCorrect: false, explanation: 'Người sinh tại Nghệ An' },
        ],
        explanation: 'Chủ tịch Hồ Chí Minh sinh ngày 19/5/1890 tại làng Sen, Kim Liên, Nghệ An',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['lịch sử', 'việt nam', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Đặc điểm thực vật',
        content: 'Cây xanh hút khí CO2 và thải ra O2?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          {
            text: 'Đúng',
            isCorrect: true,
            explanation: 'Cây quang hợp: hút CO2 + nước + ánh sáng → O2 + glucose',
          },
          { text: 'Sai', isCorrect: false, explanation: 'Đây là quá trình quang hợp của cây' },
        ],
        explanation: 'Quang hợp: cây hút CO2 và nước, với ánh sáng mặt trời tạo ra O2 và glucose',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 2,
        class: CLASS_4,
        tags: ['sinh học', 'quang hợp', 'lớp 3'],
        isActive: true,
      },

      // Single Choice Questions - Medium (12 câu)
      {
        title: 'Phép nhân lớn hơn',
        content: '7 × 8 = ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '54', isCorrect: false, explanation: '7 × 8 không bằng 54' },
          { text: '56', isCorrect: true, explanation: '7 × 8 = 56' },
          { text: '58', isCorrect: false, explanation: '7 × 8 không bằng 58' },
          { text: '60', isCorrect: false, explanation: '7 × 8 không bằng 60' },
        ],
        explanation: 'Phép nhân: 7 nhân 8 bằng 56',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'nhân', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phép chia có dư',
        content: '23 ÷ 5 = ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '4 dư 3', isCorrect: true, explanation: '23 = 5 × 4 + 3' },
          { text: '4 dư 2', isCorrect: false, explanation: '23 ÷ 5 = 4 dư 3' },
          { text: '5 dư 3', isCorrect: false, explanation: '23 ÷ 5 = 4 dư 3' },
          { text: '4 dư 4', isCorrect: false, explanation: '23 ÷ 5 = 4 dư 3' },
        ],
        explanation: 'Phép chia có dư: 23 chia 5 được 4 dư 3',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'chia', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Diện tích hình chữ nhật',
        content: 'Diện tích hình chữ nhật dài 6cm, rộng 4cm là?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '20 cm²', isCorrect: false, explanation: 'Diện tích = dài × rộng = 6 × 4 = 24' },
          { text: '24 cm²', isCorrect: true, explanation: 'Diện tích = 6 × 4 = 24 cm²' },
          { text: '26 cm²', isCorrect: false, explanation: 'Diện tích = dài × rộng = 6 × 4 = 24' },
          { text: '28 cm²', isCorrect: false, explanation: 'Diện tích = dài × rộng = 6 × 4 = 24' },
        ],
        explanation: 'Diện tích hình chữ nhật = dài × rộng = 6 × 4 = 24 cm²',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'diện tích', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Quy đổi đơn vị',
        content: '2 giờ = ? phút',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: '100 phút',
            isCorrect: false,
            explanation: '1 giờ = 60 phút, nên 2 giờ = 120 phút',
          },
          {
            text: '110 phút',
            isCorrect: false,
            explanation: '1 giờ = 60 phút, nên 2 giờ = 120 phút',
          },
          { text: '120 phút', isCorrect: true, explanation: '2 × 60 = 120 phút' },
          {
            text: '130 phút',
            isCorrect: false,
            explanation: '1 giờ = 60 phút, nên 2 giờ = 120 phút',
          },
        ],
        explanation: 'Quy đổi: 1 giờ = 60 phút, vậy 2 giờ = 2 × 60 = 120 phút',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'đơn vị', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chuỗi thức ăn',
        content: 'Trong chuỗi thức ăn: Cỏ → Thỏ → Chồn, ai là động vật ăn thịt?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Cỏ', isCorrect: false, explanation: 'Cỏ là thực vật' },
          { text: 'Thỏ', isCorrect: false, explanation: 'Thỏ ăn cỏ (động vật ăn thực vật)' },
          { text: 'Chồn', isCorrect: true, explanation: 'Chồn ăn thỏ (động vật ăn thịt)' },
          { text: 'Tất cả', isCorrect: false, explanation: 'Chỉ có chồn là động vật ăn thịt' },
        ],
        explanation: 'Chồn là động vật ăn thịt, ăn thỏ trong chuỗi thức ăn',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['sinh học', 'chuỗi thức ăn', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Trạng thái vật chất',
        content: 'Nước đóng băng ở nhiệt độ nào?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '0°C', isCorrect: true, explanation: 'Nước đóng băng ở 0°C' },
          { text: '10°C', isCorrect: false, explanation: 'Nước đóng băng ở 0°C' },
          { text: '100°C', isCorrect: false, explanation: 'Nước sôi ở 100°C' },
          { text: '-10°C', isCorrect: false, explanation: 'Nước đóng băng ở 0°C' },
        ],
        explanation: 'Điểm đóng băng của nước là 0°C (độ C)',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['khoa học', 'vật lý', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Hệ mặt trời',
        content: 'Hành tinh nào gần Mặt trời nhất?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Trái Đất', isCorrect: false, explanation: 'Trái Đất là hành tinh thứ 3' },
          { text: 'Sao Kim', isCorrect: false, explanation: 'Sao Kim là hành tinh thứ 2' },
          { text: 'Sao Thủy', isCorrect: true, explanation: 'Sao Thủy gần Mặt trời nhất' },
          { text: 'Sao Hỏa', isCorrect: false, explanation: 'Sao Hỏa là hành tinh thứ 4' },
        ],
        explanation: 'Sao Thủy là hành tinh gần Mặt trời nhất trong hệ mặt trời',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['khoa học', 'thiên văn', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Địa lý Việt Nam',
        content: 'Sông nào dài nhất Việt Nam?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: 'Sông Hồng', isCorrect: false, explanation: 'Sông Hồng không phải dài nhất' },
          { text: 'Sông Mê Kông', isCorrect: true, explanation: 'Sông Mê Kông dài nhất Việt Nam' },
          { text: 'Sông Đồng Nai', isCorrect: false, explanation: 'Sông Đồng Nai không dài nhất' },
          {
            text: 'Sông Cửu Long',
            isCorrect: false,
            explanation: 'Đây là tên khác của sông Mê Kông',
          },
        ],
        explanation: 'Sông Mê Kông (hay sông Cửu Long) là sông dài nhất chảy qua Việt Nam',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['địa lý', 'việt nam', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Lễ hội truyền thống',
        content: 'Tết Nguyên Đán là lễ hội gì?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: 'Lễ hội mùa thu',
            isCorrect: false,
            explanation: 'Tết Nguyên Đán không phải lễ hội mùa thu',
          },
          {
            text: 'Năm mới âm lịch',
            isCorrect: true,
            explanation: 'Tết Nguyên Đán là năm mới theo âm lịch',
          },
          {
            text: 'Lễ hội mùa xuân',
            isCorrect: false,
            explanation: 'Tết diễn ra vào mùa xuân nhưng bản chất là năm mới âm lịch',
          },
          {
            text: 'Lễ hội mùa đông',
            isCorrect: false,
            explanation: 'Tết Nguyên Đán không phải lễ hội mùa đông',
          },
        ],
        explanation: 'Tết Nguyên Đán là lễ đón năm mới theo âm lịch của người Việt',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['văn hóa', 'lễ hội', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phép tính hỗn hợp',
        content: '(15 + 5) ÷ 4 = ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '4', isCorrect: false, explanation: '(15 + 5) ÷ 4 = 20 ÷ 4 = 5' },
          { text: '5', isCorrect: true, explanation: '15 + 5 = 20, rồi 20 ÷ 4 = 5' },
          { text: '6', isCorrect: false, explanation: '(15 + 5) ÷ 4 = 20 ÷ 4 = 5' },
          { text: '8', isCorrect: false, explanation: '(15 + 5) ÷ 4 = 20 ÷ 4 = 5' },
        ],
        explanation: 'Thứ tự tính toán: trong ngoặc trước, (15 + 5) = 20, rồi 20 ÷ 4 = 5',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'thứ tự phép tính', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'So sánh phân số',
        content: 'Phân số nào lớn nhất: 1/2, 1/3, 1/4?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '1/2', isCorrect: true, explanation: '1/2 = 0.5 > 1/3 ≈ 0.33 > 1/4 = 0.25' },
          { text: '1/3', isCorrect: false, explanation: '1/2 lớn hơn 1/3' },
          { text: '1/4', isCorrect: false, explanation: '1/2 lớn hơn 1/4' },
          { text: 'Bằng nhau', isCorrect: false, explanation: 'Các phân số khác nhau' },
        ],
        explanation: 'So sánh phân số cùng tử số: mẫu số càng nhỏ thì phân số càng lớn',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'phân số', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Đơn vị đo khối lượng',
        content: '1 kg = ? gram',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          { text: '100 gram', isCorrect: false, explanation: '1 kg = 1000 gram' },
          { text: '500 gram', isCorrect: false, explanation: '1 kg = 1000 gram' },
          { text: '1000 gram', isCorrect: true, explanation: '1 kilogram = 1000 gram' },
          { text: '1500 gram', isCorrect: false, explanation: '1 kg = 1000 gram' },
        ],
        explanation: 'Quy đổi khối lượng: 1 kilogram = 1000 gram',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'đơn vị', 'lớp 3'],
        isActive: true,
      },

      // Multiple Choice Questions - Medium (5 câu)
      {
        title: 'Chọn các số chia hết cho 3',
        content: 'Số nào chia hết cho 3?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: '9', isCorrect: true, explanation: '9 ÷ 3 = 3' },
          { text: '10', isCorrect: false, explanation: '10 không chia hết cho 3' },
          { text: '12', isCorrect: true, explanation: '12 ÷ 3 = 4' },
          { text: '15', isCorrect: true, explanation: '15 ÷ 3 = 5' },
          { text: '17', isCorrect: false, explanation: '17 không chia hết cho 3' },
        ],
        explanation: 'Số chia hết cho 3 khi tổng các chữ số chia hết cho 3',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 4,
        class: CLASS_4,
        tags: ['toán', 'chia hết', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các hành tinh trong hệ mặt trời',
        content: 'Đâu là các hành tinh trong hệ mặt trời?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: 'Trái Đất', isCorrect: true, explanation: 'Trái Đất là hành tinh thứ 3' },
          { text: 'Mặt Trời', isCorrect: false, explanation: 'Mặt Trời là ngôi sao' },
          { text: 'Sao Hỏa', isCorrect: true, explanation: 'Sao Hỏa là hành tinh thứ 4' },
          { text: 'Mặt Trăng', isCorrect: false, explanation: 'Mặt Trăng là vệ tinh của Trái Đất' },
          { text: 'Sao Kim', isCorrect: true, explanation: 'Sao Kim là hành tinh thứ 2' },
        ],
        explanation: 'Hệ mặt trời có 8 hành tinh quay quanh Mặt Trời',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 4,
        class: CLASS_4,
        tags: ['khoa học', 'thiên văn', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các động vật có xương sống',
        content: 'Động vật nào có xương sống?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: 'Cá', isCorrect: true, explanation: 'Cá có xương sống' },
          { text: 'Bướm', isCorrect: false, explanation: 'Bướm không có xương sống' },
          { text: 'Chim', isCorrect: true, explanation: 'Chim có xương sống' },
          { text: 'Sên', isCorrect: false, explanation: 'Sên không có xương sống' },
          { text: 'Rắn', isCorrect: true, explanation: 'Rắn có xương sống' },
        ],
        explanation: 'Động vật có xương sống gồm: cá, chim, thú, bò sát, lưỡng cư',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 4,
        class: CLASS_4,
        tags: ['sinh học', 'động vật', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các nguồn năng lượng tái tạo',
        content: 'Đâu là nguồn năng lượng tái tạo?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          {
            text: 'Năng lượng mặt trời',
            isCorrect: true,
            explanation: 'Mặt trời là nguồn năng lượng tái tạo',
          },
          { text: 'Than đá', isCorrect: false, explanation: 'Than đá là năng lượng không tái tạo' },
          {
            text: 'Năng lượng gió',
            isCorrect: true,
            explanation: 'Gió là nguồn năng lượng tái tạo',
          },
          { text: 'Dầu mỏ', isCorrect: false, explanation: 'Dầu mỏ là năng lượng không tái tạo' },
          {
            text: 'Năng lượng nước',
            isCorrect: true,
            explanation: 'Nước là nguồn năng lượng tái tạo',
          },
        ],
        explanation: 'Năng lượng tái tạo từ tự nhiên: mặt trời, gió, nước, địa nhiệt',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 4,
        class: CLASS_4,
        tags: ['khoa học', 'năng lượng', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn các đặc điểm của mùa thu',
        content: 'Mùa thu có đặc điểm gì?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          {
            text: 'Lá cây chuyển màu',
            isCorrect: true,
            explanation: 'Mùa thu lá cây chuyển màu vàng, đỏ',
          },
          { text: 'Trời rất nóng', isCorrect: false, explanation: 'Mùa thu thời tiết mát mẻ' },
          { text: 'Lá cây rụng nhiều', isCorrect: true, explanation: 'Mùa thu là mùa lá rụng' },
          { text: 'Hoa nở rộ', isCorrect: false, explanation: 'Mùa xuân mới là mùa hoa nở' },
          { text: 'Thời tiết mát mẻ', isCorrect: true, explanation: 'Mùa thu thời tiết dễ chịu' },
        ],
        explanation: 'Mùa thu: lá chuyển màu và rụng, thời tiết mát mẻ',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 4,
        class: CLASS_4,
        tags: ['khoa học', 'mùa', 'lớp 3'],
        isActive: true,
      },

      // Fill in the Blank Questions - Medium (5 câu)
      {
        title: 'Điền kết quả phép chia',
        content: '56 ÷ 8 = ___',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '7', isCorrect: true, explanation: '56 ÷ 8 = 7' },
          { text: 'bảy', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        explanation: 'Phép chia: 56 chia 8 bằng 7',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'chia', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền chu vi hình vuông',
        content: 'Chu vi hình vuông cạnh 6cm là ___ cm',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '24', isCorrect: true, explanation: 'Chu vi = 4 × 6 = 24cm' },
          { text: 'hai mươi bốn', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        explanation: 'Chu vi hình vuông = 4 × cạnh = 4 × 6 = 24cm',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['toán', 'chu vi', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền tên hành tinh',
        content: 'Hành tinh chúng ta đang sống là ___',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          {
            text: 'Trái Đất',
            isCorrect: true,
            explanation: 'Chúng ta sống trên hành tinh Trái Đất',
          },
          { text: 'trai dat', isCorrect: true, explanation: 'Viết không dấu cũng được' },
          { text: 'TRÁI ĐẤT', isCorrect: true, explanation: 'Viết hoa cũng được' },
        ],
        explanation: 'Trái Đất là hành tinh thứ 3 trong hệ mặt trời, nơi con người sinh sống',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['khoa học', 'thiên văn', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền số hành tinh',
        content: 'Hệ mặt trời có ___ hành tinh',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '8', isCorrect: true, explanation: 'Hệ mặt trời có 8 hành tinh' },
          { text: 'tám', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        explanation:
          'Hệ mặt trời có 8 hành tinh: Thủy, Kim, Địa, Hỏa, Mộc, Thổ, Thiên Vương, Hải Vương',
        difficulty: DIFFICULTY_LEVELS.MEDIUM,
        points: 3,
        class: CLASS_4,
        tags: ['khoa học', 'thiên văn', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền đơn vị đo diện tích',
        content: 'Diện tích được đo bằng đơn vị ___',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          {
            text: 'cm²',
            isCorrect: true,
            explanation: 'cm² (xăng-ti-mét vuông) là đơn vị diện tích',
          },
          { text: 'm²', isCorrect: true, explanation: 'm² (mét vuông) cũng là đơn vị diện tích' },
          { text: 'vuông', isCorrect: true, explanation: 'Đơn vị diện tích có dạng vuông' },
        ],
        tags: ['toán', 'diện tích', 'lớp 3'],
        isActive: true,
      },

      // HARD DIFFICULTY QUESTIONS (20 câu)
      // True/False Questions - Hard (5 câu)
      {
        title: 'Phép tính phức tạp',
        content: '15 × 6 - 18 ÷ 3 = 84 là phép tính đúng?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          {
            text: 'Đúng',
            isCorrect: true,
            explanation: '15 × 6 = 90, 18 ÷ 3 = 6, nên 90 - 6 = 84',
          },
          { text: 'Sai', isCorrect: false, explanation: 'Phép tính này đúng' },
        ],
        explanation:
          'Thứ tự phép tính: nhân chia trước, cộng trừ sau. 15 × 6 = 90, 18 ÷ 3 = 6, rồi 90 - 6 = 84',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 4,
        class: CLASS_4,
        tags: ['toán', 'thứ tự phép tính', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phân số so sánh',
        content: '2/3 > 3/5 là so sánh đúng?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          { text: 'Đúng', isCorrect: true, explanation: '2/3 = 10/15, 3/5 = 9/15, nên 2/3 > 3/5' },
          { text: 'Sai', isCorrect: false, explanation: '2/3 thực sự lớn hơn 3/5' },
        ],
        explanation: 'Quy đồng mẫu số: 2/3 = 10/15 và 3/5 = 9/15, vậy 2/3 > 3/5',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 4,
        class: CLASS_4,
        tags: ['toán', 'phân số', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chu kỳ sinh học',
        content: 'Ếch trưởng thành từ nòng nọc qua quá trình biến thái?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          {
            text: 'Đúng',
            isCorrect: true,
            explanation: 'Ếch có chu kỳ sống: trứng → nòng nọc → ếch con → ếch trưởng thành',
          },
          { text: 'Sai', isCorrect: false, explanation: 'Đây là quá trình biến thái của ếch' },
        ],
        explanation: 'Biến thái: quá trình động vật thay đổi hình dạng từ nhỏ đến lớn',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 4,
        class: CLASS_4,
        tags: ['sinh học', 'biến thái', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Lịch sử phức tạp',
        content: 'Việt Nam có 54 dân tộc anh em?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          {
            text: 'Đúng',
            isCorrect: true,
            explanation: 'Việt Nam có 54 dân tộc với dân tộc Kinh đông nhất',
          },
          { text: 'Sai', isCorrect: false, explanation: 'Việt Nam thực sự có 54 dân tộc' },
        ],
        explanation: 'Việt Nam là quốc gia đa dân tộc với 54 dân tộc anh em',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 4,
        class: CLASS_4,
        tags: ['lịch sử', 'dân tộc', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Hiện tượng tự nhiên',
        content: 'Cầu vồng xuất hiện khi có mưa và nắng cùng lúc?',
        type: QUESTION_TYPES.TRUE_FALSE,
        answers: [
          {
            text: 'Đúng',
            isCorrect: true,
            explanation: 'Cầu vồng tạo thành khi ánh sáng mặt trời chiếu qua các giọt nước mưa',
          },
          { text: 'Sai', isCorrect: false, explanation: 'Cần có cả mưa và nắng để tạo cầu vồng' },
        ],
        explanation: 'Cầu vồng: hiện tượng khúc xạ ánh sáng qua các giọt nước trong không khí',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 4,
        class: CLASS_4,
        tags: ['khoa học', 'quang học', 'lớp 3'],
        isActive: true,
      },

      // Single Choice Questions - Hard (8 câu)
      {
        title: 'Bài toán ứng dụng',
        content:
          'Một lớp học có 24 học sinh. Nếu chia thành các nhóm 6 người thì có mấy nhóm? Nếu thiếu 2 người thì chia được mấy nhóm?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: '4 nhóm, sau đó 3 nhóm và dư 4 người',
            isCorrect: true,
            explanation: '24÷6=4 nhóm. 22÷6=3 nhóm dư 4 người',
          },
          {
            text: '4 nhóm, sau đó 4 nhóm',
            isCorrect: false,
            explanation: 'Khi thiếu 2 người chỉ còn 22 người',
          },
          { text: '6 nhóm, sau đó 5 nhóm', isCorrect: false, explanation: '24÷6=4, không phải 6' },
          {
            text: '3 nhóm, sau đó 3 nhóm',
            isCorrect: false,
            explanation: '24÷6=4 nhóm, không phải 3',
          },
        ],
        explanation: 'Bài toán chia: 24÷6=4 nhóm. Khi thiếu 2 người: 22÷6=3 nhóm dư 4 người',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['toán', 'ứng dụng', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Tính diện tích phức hợp',
        content: 'Một hình chữ nhật có chu vi 20cm và chiều dài gấp đôi chiều rộng. Diện tích là?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: '22 cm²',
            isCorrect: true,
            explanation: 'Rộng: 20÷6=10/3≈3.33cm, Dài: 20/3≈6.67cm, S≈22cm²',
          },
          { text: '25 cm²', isCorrect: false, explanation: 'Cần tính từ chu vi trước' },
          {
            text: '30 cm²',
            isCorrect: false,
            explanation: 'Cần áp dụng công thức chu vi để tìm kích thước',
          },
          { text: '16 cm²', isCorrect: false, explanation: 'Tính toán chưa chính xác' },
        ],
        explanation:
          'Chu vi = 2(d+r) = 20, d=2r → 2(2r+r) = 20 → 6r = 20 → r=10/3, d=20/3 → S=22.22≈22cm²',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['toán', 'hình học nâng cao', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chuỗi thức ăn phức tạp',
        content:
          'Trong hệ sinh thái rừng: Cỏ → Thỏ → Cáo → Sói. Nếu số lượng cáo giảm, điều gì xảy ra?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: 'Thỏ tăng, cỏ giảm, sói giảm',
            isCorrect: true,
            explanation: 'Ít cáo → nhiều thỏ → ít cỏ → ít thức ăn cho sói',
          },
          {
            text: 'Tất cả đều tăng',
            isCorrect: false,
            explanation: 'Cân bằng sinh thái không hoạt động như vậy',
          },
          { text: 'Tất cả đều giảm', isCorrect: false, explanation: 'Thỏ sẽ tăng khi ít kẻ thù' },
          {
            text: 'Không ảnh hưởng gì',
            isCorrect: false,
            explanation: 'Chuỗi thức ăn có tác động qua lại',
          },
        ],
        explanation: 'Cân bằng sinh thái: giảm cáo → tăng thỏ → giảm cỏ → giảm thức ăn → giảm sói',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['sinh học', 'hệ sinh thái', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Thiên văn nâng cao',
        content: 'Tại sao có ngày và đêm trên Trái Đất?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: 'Trái Đất tự xoay quanh trục',
            isCorrect: true,
            explanation: 'Trái Đất quay 1 vòng/24h tạo ngày đêm',
          },
          {
            text: 'Mặt Trời di chuyển',
            isCorrect: false,
            explanation: 'Mặt Trời không di chuyển quanh Trái Đất',
          },
          {
            text: 'Mặt Trăng che Mặt Trời',
            isCorrect: false,
            explanation: 'Đây là nhật thực, không phải ngày đêm',
          },
          {
            text: 'Trái Đất xa gần Mặt Trời',
            isCorrect: false,
            explanation: 'Khoảng cách không tạo ngày đêm',
          },
        ],
        explanation: 'Trái Đất tự quay quanh trục trong 24 giờ, tạo ra hiện tượng ngày và đêm',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['khoa học', 'thiên văn', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Địa lý nâng cao',
        content: 'Việt Nam có hình dạng như chữ gì?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: 'Chữ S',
            isCorrect: true,
            explanation: 'Bản đồ Việt Nam có hình dáng giống chữ S',
          },
          { text: 'Chữ C', isCorrect: false, explanation: 'Việt Nam không có hình chữ C' },
          {
            text: 'Chữ I',
            isCorrect: false,
            explanation: 'Việt Nam có nhiều uốn lượn, không thẳng như chữ I',
          },
          { text: 'Chữ O', isCorrect: false, explanation: 'Việt Nam không tròn như chữ O' },
        ],
        explanation: 'Lãnh thổ Việt Nam nhìn từ trên cao có hình dạng giống chữ S',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['địa lý', 'việt nam', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Lịch sử chi tiết',
        content: 'Việt Nam giành độc lập vào năm nào?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: '1945',
            isCorrect: true,
            explanation: 'Cách mạng tháng Tám 1945, tuyên bố độc lập 2/9/1945',
          },
          { text: '1946', isCorrect: false, explanation: 'Độc lập được tuyên bố năm 1945' },
          { text: '1975', isCorrect: false, explanation: 'Năm 1975 là thống nhất đất nước' },
          { text: '1930', isCorrect: false, explanation: 'Còn quá sớm so với độc lập' },
        ],
        explanation: 'Ngày 2/9/1945, Chủ tịch Hồ Chí Minh đọc Tuyên ngôn độc lập',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['lịch sử', 'độc lập', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Khoa học vật liệu',
        content: 'Vật liệu nào dẫn điện tốt nhất?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: 'Kim loại',
            isCorrect: true,
            explanation: 'Kim loại có electron tự do, dẫn điện tốt',
          },
          { text: 'Nhựa', isCorrect: false, explanation: 'Nhựa là chất cách điện' },
          { text: 'Gỗ', isCorrect: false, explanation: 'Gỗ khô là chất cách điện' },
          { text: 'Thủy tinh', isCorrect: false, explanation: 'Thủy tinh là chất cách điện' },
        ],
        explanation: 'Kim loại có cấu trúc electron tự do, dẫn điện và dẫn nhiệt tốt',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['khoa học', 'vật liệu', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Phép tính phân số',
        content: '1/2 + 1/3 = ?',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        answers: [
          {
            text: '5/6',
            isCorrect: true,
            explanation: '1/2 = 3/6, 1/3 = 2/6, nên 3/6 + 2/6 = 5/6',
          },
          { text: '2/5', isCorrect: false, explanation: 'Cần quy đồng mẫu số trước khi cộng' },
          {
            text: '1/5',
            isCorrect: false,
            explanation: 'Không thể cộng trực tiếp tử số và mẫu số',
          },
          { text: '3/6', isCorrect: false, explanation: 'Kết quả tính toán chưa đúng' },
        ],
        explanation: 'Cộng phân số: quy đồng mẫu số 6, rồi cộng tử số: 3/6 + 2/6 = 5/6',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['toán', 'phân số', 'lớp 3'],
        isActive: true,
      },

      // Multiple Choice Questions - Hard (4 câu)
      {
        title: 'Chọn số nguyên tố nhỏ hơn 20',
        content: 'Số nào là số nguyên tố?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: '2', isCorrect: true, explanation: '2 chỉ chia hết cho 1 và 2' },
          { text: '4', isCorrect: false, explanation: '4 chia hết cho 1, 2, 4' },
          { text: '7', isCorrect: true, explanation: '7 chỉ chia hết cho 1 và 7' },
          { text: '9', isCorrect: false, explanation: '9 chia hết cho 1, 3, 9' },
          { text: '11', isCorrect: true, explanation: '11 chỉ chia hết cho 1 và 11' },
          { text: '15', isCorrect: false, explanation: '15 chia hết cho 1, 3, 5, 15' },
        ],
        explanation: 'Số nguyên tố chỉ có đúng 2 ước: 1 và chính nó',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 6,
        class: CLASS_4,
        tags: ['toán', 'số nguyên tố', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn đặc điểm của động vật máu nóng',
        content: 'Động vật máu nóng có đặc điểm gì?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          {
            text: 'Duy trì nhiệt độ cơ thể ổn định',
            isCorrect: true,
            explanation: 'Có thể điều hòa nhiệt độ cơ thể',
          },
          {
            text: 'Nhiệt độ thay đổi theo môi trường',
            isCorrect: false,
            explanation: 'Đây là đặc điểm động vật máu lạnh',
          },
          { text: 'Có lông hoặc lớp mỡ', isCorrect: true, explanation: 'Giúp giữ nhiệt' },
          {
            text: 'Cần phơi nắng để ấm',
            isCorrect: false,
            explanation: 'Động vật máu lạnh mới cần phơi nắng',
          },
          {
            text: 'Hoạt động được trong mùa đông',
            isCorrect: true,
            explanation: 'Không bị ảnh hưởng nhiều bởi thời tiết lạnh',
          },
        ],
        explanation: 'Động vật máu nóng (chim, thú) có khả năng điều hòa nhiệt độ cơ thể',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 6,
        class: CLASS_4,
        tags: ['sinh học', 'động vật', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn nguồn gây ô nhiễm môi trường',
        content: 'Đâu là nguồn gây ô nhiễm môi trường?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          {
            text: 'Khói xe máy',
            isCorrect: true,
            explanation: 'Khí thải từ phương tiện giao thông',
          },
          { text: 'Cây xanh', isCorrect: false, explanation: 'Cây xanh làm sạch không khí' },
          { text: 'Rác thải nhựa', isCorrect: true, explanation: 'Nhựa khó phân hủy, gây ô nhiễm' },
          {
            text: 'Nước mưa',
            isCorrect: false,
            explanation: 'Nước mưa tự nhiên không gây ô nhiễm',
          },
          { text: 'Hóa chất công nghiệp', isCorrect: true, explanation: 'Chất độc hại từ nhà máy' },
        ],
        explanation: 'Ô nhiễm từ hoạt động con người: khí thải, rác thải, hóa chất',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 6,
        class: CLASS_4,
        tags: ['khoa học', 'môi trường', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Chọn thành phố lớn của Việt Nam',
        content: 'Đâu là những thành phố lớn của Việt Nam?',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        answers: [
          { text: 'Hà Nội', isCorrect: true, explanation: 'Thủ đô Việt Nam' },
          { text: 'Đà Lạt', isCorrect: false, explanation: 'Đà Lạt là thành phố nhỏ' },
          { text: 'TP. Hồ Chí Minh', isCorrect: true, explanation: 'Thành phố lớn nhất Việt Nam' },
          { text: 'Hội An', isCorrect: false, explanation: 'Hội An là thị trấn cổ nhỏ' },
          { text: 'Đà Nẵng', isCorrect: true, explanation: 'Thành phố trực thuộc trung ương' },
        ],
        explanation: 'Việt Nam có 5 thành phố trực thuộc trung ương lớn',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 6,
        class: CLASS_4,
        tags: ['địa lý', 'thành phố', 'lớp 3'],
        isActive: true,
      },

      // Fill in the Blank Questions - Hard (3 câu)
      {
        title: 'Điền kết quả phép tính phức tạp',
        content: '(12 + 8) × 3 - 15 = ___',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '45', isCorrect: true, explanation: '(12+8)×3-15 = 20×3-15 = 60-15 = 45' },
          { text: 'bốn mười lăm', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
        ],
        explanation: 'Thứ tự: ngoặc trước, nhân chia trước, cộng trừ sau',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['toán', 'phép tính phức tạp', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền tên khí quyển',
        content: 'Lớp khí bao quanh Trái Đất gọi là ___',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          {
            text: 'khí quyển',
            isCorrect: true,
            explanation: 'Atmosphere - lớp khí bao quanh hành tinh',
          },
          { text: 'khi quyen', isCorrect: true, explanation: 'Viết không dấu cũng được' },
          { text: 'atmosphere', isCorrect: true, explanation: 'Tên tiếng Anh cũng đúng' },
        ],
        explanation: 'Khí quyển chứa không khí cần thiết cho sự sống',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['khoa học', 'khí quyển', 'lớp 3'],
        isActive: true,
      },
      {
        title: 'Điền số dân tộc',
        content: 'Việt Nam có ___ dân tộc anh em',
        type: QUESTION_TYPES.FILL_BLANK,
        answers: [
          { text: '54', isCorrect: true, explanation: 'Việt Nam có 54 dân tộc' },
          { text: 'năm mươi bốn', isCorrect: true, explanation: 'Viết bằng chữ cũng đúng' },
          { text: 'năm mười bốn', isCorrect: true, explanation: 'Cách đọc khác cũng được' },
        ],
        explanation: 'Việt Nam là quốc gia đa dân tộc với 54 dân tộc anh em',
        difficulty: DIFFICULTY_LEVELS.HARD,
        points: 5,
        class: CLASS_4,
        tags: ['lịch sử', 'dân tộc', 'lớp 3'],
        isActive: true,
      },
    ]

    // Clear existing questions
    await Question.deleteMany({})

    // Insert new questions
    const createdQuestions = await Question.insertMany(questions)

    console.log(`✅ Created ${createdQuestions.length} questions for Lớp 3`)
    console.log('📝 Question breakdown:')
    console.log('   - True/False: 21 questions (8 Easy + 8 Medium + 5 Hard)')
    console.log('   - Single Choice: 32 questions (12 Easy + 12 Medium + 8 Hard)')
    console.log('   - Multiple Choice: 14 questions (5 Easy + 5 Medium + 4 Hard)')
    console.log('   - Fill in the Blank: 13 questions (5 Easy + 5 Medium + 3 Hard)')
    console.log('🎯 Difficulty levels: Easy (30), Medium (30), Hard (20)')
    console.log('🏫 Class: Lớp 3 (LOP_3)')
    console.log('📚 Subjects: Toán, Sinh học, Khoa học, Địa lý, Lịch sử, Văn hóa')

    return createdQuestions
  }
}
